### ISSUE TITLE
有没有考虑过支持url combo呢？

### ISSUE THREAD

**Issue by richardchen85** [fex-team/fis3-server-node#1]
我知道fis主要还是用的文件合并的方式来打包资源，但是有时候使用url combo的方式还是比较灵活，比如我们项目的公共资源，我们比较喜欢使用url combo，但是目前又不支持，如果可以加上的话，将非常感谢

**Comment by oxUnd** [comment]
暂时来看，FIS 的打包支持方式综合了缓存、易用性以及可操作性等几个方面，看情况是比较优的一种解。

对于 combo 暂时没有具体的计划，但如果你感兴趣，combo 实现起来其实蛮简单的。

**Comment by richardchen85** [comment]
OK，目前我也只需要在server支持一下combo，历史原因在使用seajs，不过问题不大，自己加几行代码免强可以使用
